### ISSUE TITLE
Monster abilities in the arena (Chapter 2) are affected by randomization

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#7] opened 2016-08-09 19:01 UTC
Vivian and Linguar in the following seed had random abilities assigned to them. Linguar had a high crit chance, was able to poison me and cast sleep. Vivian cast Upper/Increase and Stop Spell. 

Seed - 1199692821

Options:

Random Chapter 1-4 Heroes
Random Chapter 5 Hero Acquisition
Random Monster Zones
Random Monster Stats - Light
Random Treasures
Random Stores
Random Hero Stats - Light
Random XP Gain
Random Gold Gain
Speed Up Battles

**Comment by gameboy9** [comment] 2016-08-09 19:33
This is by design.  But the abilities used should not be absolutely crazy, and I don't think those are crazy.  However, I'm posting an enhancement, separating monster stats and monster abilities. (along with monster resistances)

**Comment by Zombietraine** [comment] 2016-08-09 19:35
Awesome! Only mentioned it becuase I saw this as part of the features section...

"Can randomize monsters/boss fights(the main boss will still be there, but who joins him would be randomized. The Chapter 2 Tournament is excluded from all randomization, however, for fairness purposes)"

**Comment by gameboy9** [comment] 2016-08-12 18:01
I renamed the quote you mentioned this morning in the README by saying that no other monster specifically can join the Chapter 2 tournament.  (That should clarify that the monster abilities can be randomized there)

**Comment by gameboy9** [comment] 2016-08-15 17:44
Implemented successfully, so I'm closing this one.

**Closed by gameboy9** 2016-08-15 17:44 UTC
Labels: enhancement
