### ISSUE TITLE
Mystic Acorns Sell For Incorrect Amount

### ISSUE THREAD

**Issue by Zombietraine** [gameboy9/DW4RandoHacker#18] opened 2016-08-16 00:50 UTC
Looks like Mystic Acorns are still a bit bugged. I was able to sell them for 2250G.

Seed 1395648915
Randomized: (Light) - Chapter 1-4 Heroes, Chapter 5 Hero Acquisition, Monster Zones, Monster Stats, Treasures, Stores, Hero Stats. 

Adjustments: Exp 150%, Gold 150%, Chapter 3 Shop and Tunnel Cost 1G, Battle Speed Increased, Control of Chapter 5 Heroes.  

![mysticacorns](https://cloud.githubusercontent.com/assets/20928976/17684456/da71c880-6329-11e6-80e6-0ecf2c0e166f.png)

**Comment by gameboy9** [comment] 2016-08-16 11:55
I intentionally adjusted the mystic acorns price to 3,000 gold because they can be bought at a randomized shop, casino, or small medal king.  Some other items were re-priced as well, partially so they can be sold at the store.  The question, however, is are they properly priced...

**Comment by Zombietraine** [comment] 2016-08-16 13:50
Oh cool! Good to know. Is there a list that has the items that are adjusted and what their prices should be so I could keep an eye out for them?

**Comment by gameboy9** [comment] 2016-08-16 14:10
I don't have that yet.  I'll get that to you soon though.

**Comment by gameboy9** [comment] 2016-08-16 17:51
00 - Cypress Stick - 10
01 - Club - 30
02 - Copper Sword - 100
03 - Iron Claw - 1500
04 - Chain Sickle - 550
05 - Iron Spear - 880
06 - Broad Sword - 2000
07 - Battle Axe - 5500
08 - Silver Tarot Cards - 500
09 - Thorn Whip - 200
0A - Morning Star - 1250
0B - Boomerang - 350
0C - Abacus of Virtue - 1600
0D - Iron Fan - 620
0E - Metal Babble Sword - 50000
0F - Poison Needle - 1400
10 - Staff Of Force - 2500
11 - Staff of Thunder - 20000
12 - Demon Hammer - 600
13 - Multi-edge Sword - 3300
14 - Zenithian Sword - 0
15 - Dragon Killer - 50000 (need to fix that)
16 - Stilleto Earrings - 7500
17 - Staff of Punishment - 4300
18 - Sword of Lethargy - 8000
19 - Venomous Dagger - 750
1A - Fire Claw - 10000
1B - Ice Blade - 20000
1C - Sword of Miracles - 30000
1D - Staff of Antimagic - 4000
1E - Magma Staff - 0
1F - Sword of Decimation - 4000
20 - Staff of Healing - 6000
21 - Zenithian Sword (Enhanced?) - 0
22 - Staff of Jubilation - 4000
23 - Sword of Malice - 3500

24 - Basic Clothes - 10
25 - Wayfarer's Clothes - 70
26 - Leather Armor - 180
27 - Chain Mail - 350
28 - Half Plate Armor - 1200
29 - Iron Apron - 1500
2A - Full Plate Armor - 2300
2B - Silk Robe - 110
2C - Dancer's Costume - 400
2D - Bronze Armor - 700
2E - Metal Babble Armor - 15000
2F - Fur Coat - 600
30 - Leather Dress - 250
31 - Pink Leotard - 6300
32 - Dragon Mail - 5200
33 - Cloak of Evasion - 3000
34 - Sacred Robe - 4400
35 - Water Flying Clothes - 15000
36 - Mysterious Bolero - 7500
37 - Zenithian Armor - 0
38 - Swordedge Armor - 9800
39 - Robe of Serenity - 6000
3A - Zombie Mail - 870
3B - Dress of Radiance - 8800
3C - Demon Armor - 1000

3D - Leather Shield - 90
3E - Scale Shield - 180
3F - Iron Shield - 650
40 - Shield of Strength - 13000
41 - Mirror Shield - 9000
42 - Aeolus' Shield - 4700
43 - Dragon Shield - 7100
44 - Zenithian Shield - 0
45 - Metal Babble Shield - 50000

46 - Leather Hat - 65
47 - Wooden Hat - 120
48 - Iron Helmet - 1100
49 - Iron Mask - 3500
4A - Feather Hat - 280
4B - Zenithian Helm - 0
4C - Mask of Corruption - 8
4D - Golden Barrette - 540
4E - Hat of Happiness - 15000
4F - Metal Babble Helm - 50000

50 - Meteorite Armband - 5000
51 - ????????????????? - 1000
52 - Baron's Horn - 0
53 - Medical Herb - 8
54 - Antidote Herb - 10
55 - Fairy Water - 20
56 - Wing of Wyvern - 25
57 - Leaf of World Tree - 10000
58 - Full Moon Herb - 30
59 - Wizard's Ring - 6000
5A - Magic Potion - 500
5B - Dew of World Tree - 10000
5C - Flute of Uncovering - 0
5D - Sphere of Silence - 0
5E - Scent Pouch - 150
5F - Sandglass of Regression - 0
60 - Sage's Stone - 0
61 - Strength Seed - 2000
62 - Agility Seed - 1500
63 - Luck Seed - 700
64 - Lifeforce Nuts - 2000
65 - Mystic Acorns - 3000
66 - Mirror of Ra - 5
67 - Lamp of Darkness - 5
68 - Staff of Transform - 0
69 - Small Medal - 4000
6A - Stone of Drought - 0
6B - Iron Safe - 0
6C - Flying Shoes - 0
6D - Silver Statuette - 0
6E - Treasure Map - 1000
6F - Symbol of Faith - 0
70 - Gunpoweder Jar - 0
71 - Thief's Key - 0
72 - Magic Key - 0
73 - Final Key - 0
74 - Lunch - 10
75 - Birdsong Nectar - 0
76 - Golden Bracelet - 0
77 - Prince's Letter - 0
78 - Royal Scroll - 0
79 - Gum Pod - 2
7A - Boarding Pass - 0
7B - Padequia Root - 0
7C - Fire of Serenity - 0
7D - Gas Canister - 0
7E - Padequia Seed - 0

**Comment by Zombietraine** [comment] 2016-08-17 11:40
Awesome! Thanks.

**Comment by gameboy9** [comment] 2016-08-22 11:15
With the Dragon Killer adjusted to the correct amount in version 0.8.0, I am going to close this issue.

**Closed by gameboy9** 2016-08-22 11:15 UTC
Labels: question
