### ISSUE TITLE
Important item problems.

### ISSUE THREAD

**Issue by Shoobers** [gameboy9/DW4RandoHacker#4] opened 2016-08-08 03:46 UTC
As we've discussed:
I was able to find 2 lamps of darkness ( one in chapter 1, chapter 2 )
Two treasure maps ( chapter 1 )
Needless to say this is overkill for chapter 1 as it clogs the character's inventory space.
Did not find the Golden Bracer but got the Thief's key early.
Iron safe in Golden Bracer chest.
Silver Statuette in Endor castle side chest.
Somehow in Chapter 3, Ragnar's inventory for the shopkeeps used the Hero's inventory ( whom was already used in the previous chapter ).
Gunpowder Jar was not found in a seed done by Zombietraine
Symbol of Faith was not found in a race seed done by Cowness and I ( somehow Zombietraine got a different seed, unsure how.  Could have something to do with sex of hero. ) Seed used: 298294828

It seems important items get shuffled to dangerous locations.

**Comment by gameboy9** [comment] 2016-08-08 13:14
The Lamp Of Darkness and Treasure Maps should become unique items.  They can be found anywhere, but there should only be one.  The Iron Safe needs to be unique only to Chapter 3.  The items earned in Endor Castle in Chapters 2 and 3 need to be moved to a "dead zone".  The Silver Statuette and Gunpowder Jar are noted as well.  I'm thinking a lot of this is because I placed treasures using a one-based array, not a zero-based array that was required.

The Golden Bracelet being missing might be intentional; since getting the Thief's Key after that is "busy work".  If that's the case though, then I need to adjust a trigger so Frenor is "post Thief Key".

TheCowness tells me that the Symbol Of Faith should have been found in one of the Woodman's Shack jars, but it was empty instead.  Therefore, I might have to move those jars to the "dead zone".

I think I need to find a straight LDA in a trace to take care of the Chapter 3 armor/Nera inventory issue.

Finally, I need to add flags, which will be performed in version 0.7.0.

All work on this should begin this week, and hopefully will be completed at that time.

**Comment by Shoobers** [comment] 2016-08-08 19:19
Cool beans.

**Comment by gameboy9** [comment] 2016-08-09 12:44
This should all be fixed in version 0.6.8... or at least that's the hope.  I'll leave this issue open though in case something else comes up.  Thanks!

**Comment by Shoobers** [comment] 2016-08-09 22:54
SOO
Just tried out the new version...

..
Uhm, how does one have 0 vitality?

**Comment by gameboy9** [comment] 2016-08-09 23:01
I worked on that over the last couple of hours.  Check out version 0.6.10.  Unless you did ludicrous stat randomization, then it's a completely random number from 0 to 31.

**Comment by Shoobers** [comment] 2016-08-09 23:03
Ofcourse I did ludicrous :P

**Comment by Shoobers** [comment] 2016-08-09 23:07
Unless the casino thing wasn't the only thing, I'll hold off until later.
Its easy enough to rig getting too many coins.
In any case, I'll be moving on from a net connection for now.   I'll be
back in about an hour or two.

**Comment by Shoobers** [comment] 2016-08-10 06:21
Received a sandglass of regression in both chapter 1 and 2.  Also with
ludicrous stat growth, there seems to be a bug between intelligence and
MP.  MP gains are 0-3 for almost everyone but their intelligence scores can
be through the roof.  Mara for example has like 146 int at level 9 but only
21 mp.

**Comment by Shoobers** [comment] 2016-08-10 07:27
Its still somehow pulling from an entirely different inventory for the
shop.  The inventory comes up appropriately but instead of dragon mail
being sold to the guy it was full plate, also half plate somehow came up as
wooden hat.  I think it was again pulling from Female Hero's inventory
slots.

**Comment by gameboy9** [comment] 2016-08-10 12:30
The sandglass of regression is now a "rare item", meaning it can only be found once.  Same for the stone of drought, and I think one or two other items.

Statistics don't quite work the same as in DW3; the MP has a separate growth statistic, meaning that it isn't necessarily 2*Intelligence.  Which then begs the question: what is intelligence used for?  Good question!  I have no idea...

I took care of the Bonmalmo Armor Donation issue, hopefully for good, in 0.6.11.  This issue didn't come up in the Endor shop though, interestingly enough...

**Comment by Zombietraine** [comment] 2016-08-10 13:10
I current have 3 sages stone's in my current run of 0.6.10. Following seed an options...

Seed - 1470868112

Options:

Random Chapter 1-4 Heroes
Random Chapter 5 Hero Acquisition
Random Monster Zones
Random Monster Stats - Light
Random Treasures
Random Stores
Random Hero Stats - Light
Random XP Gain
Random Gold Gain
Speed Up Battles

I got 1 in Chapter 1 and 2 in Chapter 2 (Lucky me! lol). Anyway, I was wondering if this should be made unique as well? I was also thinking if an option to toggle unique items on and off (in that you can get only 1 of certain items or there could be more) would be a neat addition once all unique items are determined.

**Comment by gameboy9** [comment] 2016-08-10 13:33
Ahhhh... I thought I made it a unique item already, but apparently not the case.  I'll take care of it.  That would be an interesting option, but I'm not sure if we need, for example, three final keys...

**Comment by Zombietraine** [comment] 2016-08-10 13:35
> I'm not sure if we need, for example, three final keys...

Accurate! lol

**Comment by Shoobers** [comment] 2016-08-10 15:58
attempt 2

**Comment by gameboy9** [comment] 2016-08-15 17:44
Implemented in 0.7.0, generally.  If there's a lingering or fresh bug related to this, I'd rather create a new issue at this point.  Thanks for everyone's help!  :)

**Closed by gameboy9** 2016-08-15 17:44 UTC
Labels: bug
